<a href="https://colab.research.google.com/github/christiano1974/Aulas_Est_Python_R/blob/main/autovaloresautovetoresdiagonalizacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Cálculo dos autovalores e autovetores de uma matriz (operador linear). Diagonalização de uma matriz de um operador linear.

In [ ]:
import numpy as np

In [ ]:
# matriz A
A = np.matrix('2 4 2; 1 0 1; 1 -4 5')
A

matrix([[ 2,  4,  2],
        [ 1,  0,  1],
        [ 1, -4,  5]])

In [ ]:
# os autovalores
A_autovalores, A_autovetores = np.linalg.eig(A)

In [ ]:
A_autovalores

array([ 4., -1.,  4.])

In [ ]:
A_autovetores

matrix([[ 0.90453403,  0.81649658, -0.90453403],
        [ 0.30151134, -0.40824829, -0.30151134],
        [ 0.30151134, -0.40824829, -0.30151134]])

In [ ]:
print("Lista dos autovalores da matriz A:")
for autovalor in A_autovalores:
    print(round(autovalor,0))

Lista dos autovalores da matriz A:
4.0
-1.0
4.0


In [ ]:
print("Matriz dos autovetores da matriz A:\n")
print(A_autovetores)

Matriz dos autovetores da matriz A:

[[ 0.90453403  0.81649658 -0.90453403]
 [ 0.30151134 -0.40824829 -0.30151134]
 [ 0.30151134 -0.40824829 -0.30151134]]


In [ ]:
# O determinante da matriz dos autovetores da matriz A é igual a zero. Logo,
# os vetores não são L.I. portanto a matriz A não é diagonalizável.
print("O determinante da matriz dos autovetores é igual: {}".format(np.linalg.det(A_autovetores)))
print("Como os vetores não são L.I. (são L.D.) então, a matriz A não é diagonalizável.")

O determinante da matriz dos autovetores é igual: -2.39153262986216e-16
Como os vetores não são L.I. (são L.D.) então, a matriz A não é diagonalizável.


In [ ]:
# matriz B
B = np.matrix([[3,2,1],[1,4,1],[1,2,3]])
B

matrix([[3, 2, 1],
        [1, 4, 1],
        [1, 2, 3]])

In [ ]:
B_autovalores, B_autovetores = np.linalg.eig(B)

In [ ]:
print("Lista dos autovalores da matriz B:")
for autovalor in B_autovalores:
    print(round(autovalor,0))

Lista dos autovalores da matriz B:
2.0
6.0
2.0


In [ ]:
print("Matriz dos autovetores da matriz B:\n")
print(B_autovetores)

Matriz dos autovetores da matriz B:

[[-0.90453403  0.57735027  0.17690164]
 [ 0.30151134  0.57735027 -0.50949679]
 [ 0.30151134  0.57735027  0.84209194]]


In [ ]:
# O determinante da matriz dos autovetores da matriz B é diferente de zero.
# Logo, os vetores são L.I. e daí a matriz B é diagonalizável.
np.linalg.det(B_autovetores)

-0.941125589308534

In [ ]:
# diagonalização da matriz B (D = inversa(P)*B*P ,
# onde P é a matriz dos autovetores da matriz B)
D = np.linalg.inv(B_autovetores).dot(B).dot(B_autovetores)
print("Diagonalização da matriz B:\n")
print(D.astype(int))

Diagonalização da matriz B:

[[2 0 0]
 [0 6 0]
 [0 0 1]]
