<a href="https://colab.research.google.com/github/christiano1974/Aulas_Est_Python_R/blob/main/Exerc%C3%ADcios_1_(alg_linear).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Pacote Numpy
import numpy as np

In [8]:
# Matriz A
A = np.matrix('3 2 1;0 9 2')
A

matrix([[3, 2, 1],
        [0, 9, 2]])

In [9]:
# Transposta da matriz A
A.T

matrix([[3, 0],
        [2, 9],
        [1, 2]])

In [11]:
# matriz A e matriz B
A = np.matrix('3 0;1 -5') ; B = np.matrix('2 1;3 4')

In [14]:
# Soma das matrizes A e B
print(A)
print(B)
print(A+B)

[[ 3  0]
 [ 1 -5]]
[[2 1]
 [3 4]]
[[ 5  1]
 [ 4 -1]]


In [15]:
# Multiplicação escalar com matriz
print(4*A)

[[ 12   0]
 [  4 -20]]


In [16]:
# matrizes A e B
A = np.matrix('1 0 3;2 1 4')
B = np.matrix('3 2;1 4;0 1')
print(A)
print(B)

[[1 0 3]
 [2 1 4]]
[[3 2]
 [1 4]
 [0 1]]


In [27]:
# Dimensões das matrizes A e B
print('dim A = ', A.shape, 'e dim B = ', B.shape)

dim A =  (2, 3) e dim B =  (3, 2)


In [28]:
# Produto das matrizes A por B
A@B

matrix([[ 3,  5],
        [ 7, 12]])

In [29]:
# Produto das matrizes A por B
A.dot(B)

matrix([[ 3,  5],
        [ 7, 12]])

In [31]:
# matriz A
A = np.matrix('1 0;2 1')
#Potências de A
print(np.linalg.matrix_power(A,2),'\n')
print(np.linalg.matrix_power(A,3),'\n')
print(np.linalg.matrix_power(A,4),'\n')
print(np.linalg.matrix_power(A,5))


[[1 0]
 [4 1]] 

[[1 0]
 [6 1]] 

[[1 0]
 [8 1]] 

[[ 1  0]
 [10  1]]


In [34]:
# matriz A
A = np.matrix('1 0 1;2 1 1;1 1 1')
print(A)
# inversa da matriz A
print(np.linalg.inv(A))

[[1 0 1]
 [2 1 1]
 [1 1 1]]
[[ 0.  1. -1.]
 [-1. -0.  1.]
 [ 1. -1.  1.]]


In [39]:
# Determinante da matriz A de ordem 2
A = np.matrix('3 2;1 4')
print(A)
print(int(np.linalg.det(A)))

[[3 2]
 [1 4]]
10


In [40]:
# Determinante da matriz A de ordem 3
A = np.matrix('1 3 -1;3 4 1;1 2 -1')
print(A)
print(int(np.linalg.det(A)))

[[ 1  3 -1]
 [ 3  4  1]
 [ 1  2 -1]]
4
